### ISSUE TITLE
error on final move of the engine

### ISSUE THREAD

**Issue by efirvida** [imor/uci#19]
I'm using the library with stockfish 6 and when the engine give his final best move the library raise an error "Error: Invalid format of bestmove. Expected "bestmove <move>".

var moveRegex = /bestmove (.*?) /g;
didn't match the final move expression

**Comment by efirvida** [comment]
change it for 
var moveRegex = /bestmove ([a-h][1-8][a-h][1-8]])/g

**Comment by imor** [comment]
Closing as it has been fixed by PR #20
